prompt Granting privileges for synonyms to &role_rw

GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..DOCUMENT TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..PROCESS TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..ACTION TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..PACKAGE TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..VERSION TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..ONLINE_ENQUIRY_CONTRACTS TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..ONLINE_ENQUIRY_STATUS TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..RENDERING_DOCUMENT TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..CONTRACT TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..HEALTH_MONITOR_LOGGING TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..MONITOR_LSL TO &role_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&sapp..MONITOR_HOUSEKEEPING TO &role_rw;
GRANT SELECT ON &&sapp..MONITORID_SEQ To &role_rw;
GRANT SELECT ON &&sapp..VERSION_SEQ TO &role_rw;
GRANT SELECT ON &&sapp..OECID_SEQ To &role_rw;
GRANT SELECT ON &&sapp..OESID_SEQ To &role_rw;
GRANT SELECT ON &&sapp..CONTRACTID_SEQ To &role_rw;
GRANT SELECT ON &&sapp..RENDERING_DOCUMENT_SEQ To &role_rw;
GRANT SELECT ON &&sapp..CONTRACTS_HOUSEKEEPING_SEQ TO &role_rw;


