

BEGIN 
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(1,'Банско', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(2,'Белица', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(3,'Благоевград', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(4,'Гоце Делчев', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(5,'Гърмен', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(6,'Кресна', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(7,'Петрич', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(8,'Разлог', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(9,'Сандански', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(10,'Сатовча', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(11,'Симитли', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(12,'Струмяни', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(13,'Хаджидимово', 1);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(14,'Якоруда', 1);
		
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(15,'Айтос', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(16,'Бургас', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(17,'Камено', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(18,'Карнобат', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(19,'Малко Търново', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(20,'Несебър', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(21,'Поморие', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(22,'Приморско', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(23,'Руен', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(24,'Созопол', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(25,'Средец', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(26,'Сунгурларе', 2);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(27,'Царево', 2);
		
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(28,'Аврен', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(29,'Аксаково', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(30,'Белослав', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(31,'Бяла', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(32,'Варна', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(33,'Ветрино', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(34,'Вълчи дол', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(35,'Девня', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(36,'Долни чифлик', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(37,'Дългопол', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(38,'Провадия', 3);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(39,'Суворово', 3);
		
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(40,'Велико Търново', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(41,'Горна Оряховица', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(42,'Елена', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(43,'Златарица', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(44,'Лясковец', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(45,'Павликени', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(46,'Полски Тръмбеш', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(47,'Свищов', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(48,'Стражица', 4);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(49,'Сухиндол', 4);
		
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(51,'Белоградчик', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(52,'Бойница', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(53,'Брегово', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(54,'Видин', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(55,'Грамада', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(56,'Димово', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(57,'Кула', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(58,'Макреш', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(59,'Ново село', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(60,'Ружинци', 5);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(61,'Чупрене', 5);
		
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(62,'Борован', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(63,'Бяла Слатина', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(64,'Враца', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(65,'Козлодуй', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(66,'Криводол', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(67,'Мездра', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(68,'Мизия', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(69,'Оряхово', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(70,'Роман', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(71,'Хайредин', 6);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(72,'Габрово', 7);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(73,'Дряново', 7);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(74,'Севлиево', 7);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(75,'Трявна', 7);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(76,'Балчик', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(77,'Генерал Тошево', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(78,'Добрич-селска', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(79,'Добрич', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(80,'Каварна', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(81,'Крушари', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(82,'Тервел', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(83,'Шабла', 8);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(84,'Ардино', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(85,'Джебел', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(86,'Кирково', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(87,'Крумовград', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(88,'Кърджали', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(89,'Момчилград', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(90,'Черноочене', 9);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(91,'Бобов дол', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(92,'Бобошево', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(93,'Дупница', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(94,'Кочериново', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(95,'Кюстендил', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(96,'Невестино', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(97,'Рила', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(98,'Сапарева баня', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(99,'Трекляно', 10);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(100,'Априлци', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(101,'Летница', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(102,'Ловеч', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(103,'Луковит', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(104,'Тетевен', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(105,'Троян', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(106,'Угърчин', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(107,'Ябланица', 11);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(108,'Берковица', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(109,'Бойчиновци', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(110,'Брусарци', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(111,'Вълчедръм', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(112,'Вършец', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(113,'Георги Дамяново', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(114,'Лом', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(115,'Медковец', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(116,'Монтана', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(117,'Чипровци', 12);
		INSERT INTO REGION_CITIES (ID, CITY_NAME, REGION_ID) VALUES(118,'Якимово', 12);

    COMMIT; 
EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK; 

      RAISE; 
END; 

/ 