

BEGIN 
    	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(1,'Ван',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(2,'Джип',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(3,'Кабрио',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(4,'Комби',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(5,'Купе',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(6,'Миниван',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(7,'Пикап',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(8,'Седан',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(9,'Стреч лимузина',1);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(10,'Хечбек',1);
	
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(11,'Бордови',2);
        INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(12,'Катафалка',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(13,'Линейка',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(14,'Пътнически',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(15,'Самосвал',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(16,'Самосвал с кран',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(17,'Товарен',2);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(18,'Товаропътнически',2);
    	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(19,'Фургон',2);
	
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(20,'Автовоз',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(21,'Бордови',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(22,'Влекач',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(23,'Кран',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(24,'Мултилифт',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(25,'Самосвал',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(26,'Самосвал с кран',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(27,'Снегорин',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(28,'Фургон',3);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(29,'Цистерна',3);
	
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(30,'ATV',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(31,'Cafe Racer',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(32,'UTV',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(33,'Бъги',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(34,'Ендуро',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(35,'Мото ролер',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(36,'Моторна шейна',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(37,'Кросов',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(38,'Пистов',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(39,'Скутер',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(40,'СуперМото',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(41,'Триколка',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(42,'Турър',4);
	INSERT INTO SUB_CATEGORIES (ID, NAME, MAIN_CATEGORY_ID) VALUES(43,'Чопър',4);

    COMMIT; 
EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK; 

      RAISE; 
END; 

/ 