

BEGIN 
    	INSERT INTO REGIONS (ID, REGION_NAME) VALUES(1,'Благоевград');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(2,'Бургас');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(3,'Варна');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(4,'Велико Търново');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(5,'Видин');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(6,'Враца');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(7,'Габрово');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(8,'Добрич/Толбухин');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(9,'Кърджали');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(10,'Кюстендил');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(11,'Ловеч');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(12,'Монтана');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(13,'Пазарджик');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(14,'Перник');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(15,'Плевен');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(16,'Пловдив');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(17,'Разград');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(18,'Русе');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(19,'Силистра');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(20,'Сливен');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(21,'Смолян');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(22,'София - град');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(23,'София - област');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(24,'Стара Загора');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(25,'Търговище');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(26,'Хасково');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(27,'Шумен');
		INSERT INTO REGIONS (ID, REGION_NAME) VALUES(28,'Ямбол');
		

    COMMIT; 
EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK; 

      RAISE; 
END; 

/ 