

BEGIN 
    	INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(1,'Audi','100',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(2,'Audi','200',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(3,'Audi','80',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(4,'Audi','60',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(5,'Audi','A1',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(6,'Audi','A2',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(7,'Audi','A3',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(8,'Audi','A4',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(9,'Audi','A5',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(10,'Audi','A6',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(11,'Audi','A7',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(12,'Audi','A8',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(13,'BMW','114',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(14,'BMW','116',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(15,'BMW','118',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(16,'BMW','120',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(17,'BMW','123',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(18,'BMW','125',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(19,'Subaru','Ascent',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(20,'Subaru','BRZ',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(21,'Subaru','Baja',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(22,'Subaru','Impreza',1);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(23,'Subaru','Forester',1);
		                                       
		                                       
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(24,'Kawasaki','100',4);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(25,'Kawasaki','1000',4);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(26,'Kawasaki','125',4);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(27,'Aprilia','125',4);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(28,'Aprilia','200',4);
		INSERT INTO MAKE_MODEL (ID, MAKE, MODEL, MAIN_CATEGORY_ID) VALUES(29,'Aprilia','250',4);
		
		

    COMMIT; 
EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK; 

      RAISE; 
END; 

/ 