

BEGIN 
    INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(1,'Автомобили и Джипове');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(2,'Бусове');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(3,'Камиони');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(4,'Мотоциклети');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(5,'Селскостопански');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(6,'Индустриални');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(7,'Кари');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(8,'Каравани');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(9,'Яхти и Лодки');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(10,'Ремаркета');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(11,'Велосипеди');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(12,'Части');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(13,'Аксесоари');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(14,'Гуми и джанти');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(15,'Купува');
	INSERT INTO MAIN_CATEGORIES (ID, NAME) VALUES(16,'Услуги');

    COMMIT; 
EXCEPTION 
    WHEN OTHERS THEN 
      ROLLBACK; 

      RAISE; 
END; 

/ 