CREATE OR REPLACE SYNONYM ANNOUNCEMENT_VEHICLE FOR &&sapp..ANNOUNCEMENT_VEHICLE;
CREATE OR REPLACE SYNONYM MAIN_CATEGORIES FOR &&sapp..MAIN_CATEGORIES;
CREATE OR REPLACE SYNONYM SUB_CATEGORIES FOR &&sapp..SUB_CATEGORIES;
CREATE OR REPLACE SYNONYM MAKE_MODEL FOR &&sapp..MAKE_MODEL;
CREATE OR REPLACE SYNONYM REGIONS FOR &&sapp..REGIONS;
CREATE OR REPLACE SYNONYM REGION_CITIES FOR &&sapp..REGION_CITIES;
CREATE OR REPLACE SYNONYM IMAGE_FILES FOR &&sapp..IMAGE_FILES;
CREATE OR REPLACE SYNONYM USERS FOR &&sapp..USERS;
CREATE OR REPLACE SYNONYM USER_INFO FOR &&sapp..USER_INFO;

CREATE OR REPLACE SYNONYM APP_SEQ FOR &&sapp..APP_SEQ;
