CREATE OR REPLACE SYNONYM ANNOUNCEMENTS FOR &&sapp..ANNOUNCEMENTS;
CREATE OR REPLACE SYNONYM ENUM_ITEM_BASES FOR &&sapp..ENUM_ITEM_BASES;
CREATE OR REPLACE SYNONYM MAIN_CATEGORIES FOR &&sapp..MAIN_CATEGORIES;
CREATE OR REPLACE SYNONYM SUB_CATEGORIES FOR &&sapp..SUB_CATEGORIES;

CREATE OR REPLACE SYNONYM ANNOUNCEMENTS_SEQ FOR &&sapp..ANNOUNCEMENTS_SEQ;