package tusofia.carsellservices.validation;

public enum ValidationType {
	MAIN_CATEGORY_ID, BRAND, MODEL, ENGINE_TYPE, CONDITION_TYPE, HORSE_POWER, EMISSION_STANDART_TYPE, GEARBOX_TYPE,
	SUB_CATEGORY_ID, COOLING_TYPE, NUMBER_OF_AXELS, NUMBER_OF_SEATS, WEIGHT_CAPACITY, PRICE, CURRENCY,
	DATE_OF_MANUFACTURE, MILEAGE, COLOR, REGION, CITY, VALID_DAYS, CUBATURE, ENGINE_CATEGORY_TYPE, VALID_FROM,
	TOTAL_WEIGHT, WORKING_VOLUME, HOURS_OF_OPERAITON, NUMBER_OF_BEDS, TOILET_TYPE, HEATING_TYPE, AIR_CONDITION_TYPE,
	LENGTH_SIZE, MATERIAL_TYPE, WIDTH, BICYCLE_SIZE, NUMBER_OF_GEARS, DESCIPTION, UNSUPPORTED, USER_ID
}
