prompt executing script crtb_ENUM_ITEM_BASES.sql in schema &&sapp

CREATE TABLE &&sapp..ENUM_ITEM_BASES(
  ID NUMBER (15) NOT NULL,
  NAME VARCHAR2(60 CHAR) NOT NULL,
  DISCRIMINATOR VARCHAR2(60 CHAR) NOT NULL
)
LOGGING;