prompt executing script crtb_USER_INFO.sql in schema &&sapp

CREATE TABLE &&sapp..USER_INFO(
ID NUMBER (15) NOT NULL,
FIRST_NAME VARCHAR2(255 CHAR ),
LAST_NAME VARCHAR2(255 CHAR),
USERNAME VARCHAR2(255 CHAR) NOT NULL,
EMAIL VARCHAR2(255 CHAR) NOT NULL,
TELEPHONE VARCHAR2(30 CHAR) NOT NULL,
IMAGE BLOB,
USER_ID NUMBER (15) NOT NULL,
CONSTRAINT UI_USERNAME_UNIQUE UNIQUE(USERNAME),
CONSTRAINT UI_EMAIL_UNIQUE UNIQUE(EMAIL)
);
