prompt executing script crtb_USERS.sql in schema &&sapp

CREATE TABLE &&sapp..USERS(
ID NUMBER (15) NOT NULL,
PASSWORD VARCHAR2(512 CHAR) NOT NULL,
USERNAME VARCHAR2(255 CHAR) NOT NULL,
CONSTRAINT U_USERNAME_UNIQUE UNIQUE(USERNAME)
);
