prompt Granting privileges for synonyms to &role_rw

GRANT SELECT ON &&sapp..ANNOUNCEMENTS_SEQ TO &role_rw;

GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..ANNOUNCEMENTS TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..ENUM_ITEM_BASES TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..MAIN_CATEGORIES TO &role_rw;
GRANT SELECT, INSERT, DELETE, UPDATE ON &&sapp..SUB_CATEGORIES TO &role_rw;


